/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alumni: typeof import('./src/components/Alumni.vue')['default']
    Citation: typeof import('./src/components/Citation.vue')['default']
    CitationPatent: typeof import('./src/components/CitationPatent.vue')['default']
    CitationRefactor: typeof import('./src/components/CitationRefactor.vue')['default']
    FooterBox: typeof import('./src/components/FooterBox.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    ProfilePicture: typeof import('./src/components/ProfilePicture.vue')['default']
    Publication: typeof import('./src/components/Publication.vue')['default']
    PublicationRefactor: typeof import('./src/components/PublicationRefactor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMember: typeof import('./src/components/TeamMember.vue')['default']
  }
}
